[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--version"

[build]
# for demo or preview
command = "npx pnpm i --no-frozen-lockfile --store=node_modules/.pnpm-store && pnpm run build"
publish = "dist/pre"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
