// this file is auto register for every export with prefix G eg. GFooter
export { default as GParagraph } from 'antd/es/typography/Paragraph'
export { default as GText } from 'antd/es/typography/Text'
export { default as GTitle } from 'antd/es/typography/Title'
export { default as GFooter } from './Footer'
export { default as GDrawer } from './feedback/drawer'
export { default as GModal } from './feedback/modal'
// export { default as Icon } from './Icon'
export { default as GRightContent } from './RightContent'
export { default as GDevTools } from './Tools/devTool'
export { default as GHeaderContentRender } from './layouts/headerContentRender'
